### ISSUE TITLE
Readline prompt issues, global usage

### ISSUE THREAD

**Issue by cschuijt** [cschuijt/minishell#4]
Right now, our modding of readline has caused the terminal to be mismanaged slightly, meaning line wrapping and copy-pasting looks weird. However, it is the only way in which our current implementation for setting the right return value on signal will work, and the shell behaves as intended. We could consider one of the following solutions to restore readline to its normal operation in interactive mode:

- Change the global to a struct or struct pointer, which includes the return value. This is very dicey, and we've heard of multiple people they'd fail us for this.
- Change the global to a long, or bitshift when setting/reading the return value. I think this is a more agreeable solution, but it's still storing multiple things inside a single global. It'd also take more effort to implement. Technically, an int already provides enough space, since a return value can only be 0-255.

The effort versus the reward is still a bit of a stretch, so I'm marking this as optional.

**Comment by codingfrog27** [comment]
Might also be worthwhile testing to see if removing the colour codes from our prompt fixes any issues!

**Comment by codingfrog27** [comment]
is still slightly unclear, but removing colour codes seemed to have fixed this???
