### ISSUE TITLE
Variable names should start with a letter or underscore

### ISSUE THREAD

**Issue by cschuijt** [cschuijt/minishell#6]
The first character of variables should be an uppercase letter, lowercase letter or underscore. The other characters can also be digits. Anything else should print an error and move on to the next argument.

**Comment by cschuijt** [comment]
More strictly enforcing this will also fix the issues we had with a bunch of special characters being accepted into `export`. Take extra care to not accept the equals sign as part of the variable name!

**Comment by codingfrog27** [comment]
Ah it's good u mention that! I wonder how u check for that. If u could just see if there's more than one equal sign.

But if u can have as many equals as u want in your value than I think the first one will just always count as your delimiter for going from name to value? Will test bash behavior for this ^^

**Comment by cschuijt** [comment]
I think it's mostly that the argument shouldn't start with an equals sign, much like it shouldn't start with anything else that isn't a letter or an underscore. When you enter `export ===` or `export =a`, that should error, but `export a===` should just create a variable named `a` with value `==`. So in short, the first character of the variable name needs to be a letter or underscore, the other characters before the first equals sign can also be numbers. After the equals sign, anything goes.
